package App;

import com.config.MyConfig;
import java.sql.PreparedStatement;
import java.sql.Connection;
import com.controllers.dbController;
import com.models.Produk;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author apple
 */
public class App extends javax.swing.JFrame {
    
    private int totalBelanja = 0;
    private List<Integer> selectedRowsList = new ArrayList<>();
    private boolean isEditing = false;

    private Connection Con;
    
    public void clear(){
        Tnama.setText("");
        Tharga.setText("");
        Tjumlah.setText("");
        Tnama.requestFocus();
    }
    
    public void InsertData(){
       DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
       int row = Tabel.getRowCount();
       model.addRow(new Object []{
           row += 1 ,
           Tnama.getText(),
           Tharga.getText(),
           Tjumlah.getText()
        });
    }
     public double HitungTotal(){
     DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        int rowCount = model.getRowCount();
        double total = 0.0;
        
        for(int i = 0; i < rowCount; i++){
            double harga = Double.parseDouble(model.getValueAt(i, 2).toString());
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
            total += harga*jumlah;
        }
        return total;
     }
    

    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        newTable();
    }
    
    private void newTable(){
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        model.setRowCount(0);

        List<Produk> dataList = dbController.readData();

        for (Produk data : dataList ) {
            Object[] row = {data.getId(), data.getName(), data.getPrice(), data.getStock()};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        Lshop = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Lnama = new javax.swing.JLabel();
        Lharga = new javax.swing.JLabel();
        Ljumlah = new javax.swing.JLabel();
        Tnama = new javax.swing.JTextField();
        Tharga = new javax.swing.JTextField();
        Tjumlah = new javax.swing.JTextField();
        Binsert = new javax.swing.JButton();
        Bedit = new javax.swing.JButton();
        Bdelete = new javax.swing.JButton();
        Bclear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Ltotal = new javax.swing.JLabel();
        LTunai = new javax.swing.JLabel();
        LKembali = new javax.swing.JLabel();
        Ttotal = new javax.swing.JTextField();
        Ttunai = new javax.swing.JTextField();
        Tkembali = new javax.swing.JTextField();
        Bhitung = new javax.swing.JButton();
        Bsimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        Lshop.setBackground(new java.awt.Color(255, 153, 153));
        Lshop.setFont(new java.awt.Font("Noteworthy", 3, 24)); // NOI18N
        Lshop.setForeground(new java.awt.Color(51, 0, 51));
        Lshop.setText(" CHAN SHOP CASHIER");
        Lshop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Lshop, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lshop, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        Lnama.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Lnama.setText("NAMA");

        Lharga.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Lharga.setText("HARGA");

        Ljumlah.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Ljumlah.setText("JUMLAH");

        Tnama.setBackground(new java.awt.Color(254, 191, 160));
        Tnama.setForeground(new java.awt.Color(0, 51, 51));

        Tharga.setBackground(new java.awt.Color(254, 191, 160));
        Tharga.setForeground(new java.awt.Color(51, 0, 51));

        Tjumlah.setBackground(new java.awt.Color(254, 191, 160));
        Tjumlah.setForeground(new java.awt.Color(0, 51, 0));

        Binsert.setBackground(new java.awt.Color(255, 153, 51));
        Binsert.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Binsert.setForeground(new java.awt.Color(0, 51, 51));
        Binsert.setText("Insert");
        Binsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinsertActionPerformed(evt);
            }
        });

        Bedit.setBackground(new java.awt.Color(204, 153, 0));
        Bedit.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Bedit.setText("Edit");
        Bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeditActionPerformed(evt);
            }
        });

        Bdelete.setBackground(new java.awt.Color(255, 153, 0));
        Bdelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Bdelete.setForeground(new java.awt.Color(51, 51, 51));
        Bdelete.setText("Delete");
        Bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeleteActionPerformed(evt);
            }
        });

        Bclear.setBackground(new java.awt.Color(204, 153, 0));
        Bclear.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Bclear.setText("Clear");
        Bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclearActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));

        Ltotal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Ltotal.setForeground(new java.awt.Color(242, 242, 242));
        Ltotal.setText("Total");

        LTunai.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LTunai.setForeground(new java.awt.Color(242, 242, 242));
        LTunai.setText("Tunai");

        LKembali.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LKembali.setForeground(new java.awt.Color(242, 242, 242));
        LKembali.setText("Kembali");

        Ttotal.setEditable(false);
        Ttotal.setBackground(new java.awt.Color(239, 192, 169));
        Ttotal.setForeground(new java.awt.Color(51, 51, 0));
        Ttotal.setText("Rp. ");

        Ttunai.setBackground(new java.awt.Color(239, 192, 169));
        Ttunai.setForeground(new java.awt.Color(51, 51, 0));
        Ttunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtunaiActionPerformed(evt);
            }
        });

        Tkembali.setEditable(false);
        Tkembali.setBackground(new java.awt.Color(239, 192, 169));
        Tkembali.setForeground(new java.awt.Color(51, 51, 0));
        Tkembali.setText("Rp. ");

        Bhitung.setText("Hitung");
        Bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhitungActionPerformed(evt);
            }
        });

        Bsimpan.setText("Simpan");
        Bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bhitung)
                    .addComponent(LTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ttotal)
                            .addComponent(Ttunai)
                            .addComponent(Tkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Bsimpan)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LTunai, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(Ttunai))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bhitung)
                    .addComponent(Bsimpan))
                .addGap(34, 34, 34))
        );

        Tabel.setBackground(new java.awt.Color(254, 191, 160));
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Harga", "Jumlah"
            }
        ));
        jScrollPane2.setViewportView(Tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ljumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Binsert, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Tjumlah)
                                    .addComponent(Tharga, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bclear))
                                    .addComponent(Tnama))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lnama)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tnama)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lharga)
                            .addComponent(Tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ljumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tjumlah))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Binsert, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeditActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        int rowSelect = Tabel.getSelectedRow();
        
        if (Bedit.getText() == "Edit"){
            Binsert.setEnabled(false);
            Bdelete.setEnabled(false);
            Bedit.setText("Update");
            Tnama.setText(model.getValueAt(rowSelect, 1).toString());
            Tharga.setText(model.getValueAt(rowSelect, 2).toString());
            Tjumlah.setText(model.getValueAt(rowSelect, 3).toString());
        }else{
            Binsert.setEnabled(true);
            Bdelete.setEnabled(true);
            Bedit.setText("Edit");
            
            String namabarang = Tnama.getText();
            String hargabarang = Tharga.getText();
            String jumlahbarang = Tjumlah.getText();
            
            model.setValueAt(namabarang, rowSelect, 1);
            model.setValueAt(hargabarang, rowSelect, 2);
            model.setValueAt(jumlahbarang, rowSelect, 3);
        }
    }//GEN-LAST:event_BeditActionPerformed

    private void BdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeleteActionPerformed
        int selectedRow = Tabel.getSelectedRow();
        
        if (selectedRow != -1){
            int id = (int) Tabel.getValueAt(selectedRow, 0);
            dbController.deleteData(id);
            newTable();
        } else {
        JOptionPane.showMessageDialog(null, "Belum Ada Data Terpilih");
        }
    }//GEN-LAST:event_BdeleteActionPerformed

    private void BinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinsertActionPerformed
        if (Tnama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama barang belum diinput");
        }else if(Tharga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga barang belum diinput");
        } else if (Tjumlah.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah barang belum diinput");
        }else {
            InsertData();
            clear();
            double total = HitungTotal();
            Ttotal.setText("Rp." + String.valueOf(total));
        }
    }//GEN-LAST:event_BinsertActionPerformed

    private void BclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclearActionPerformed
        clear();
        Ttotal.setText("Rp.");
        Ttunai.setText("0");
        Tkembali.setText("Rp.");
        
        newTable();
    }//GEN-LAST:event_BclearActionPerformed

    private void BhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhitungActionPerformed
        try {
        double jumlahBayar = Double.parseDouble(Ttunai.getText());
        double total = HitungTotal();
        double kembalian = jumlahBayar - total;
        Tkembali.setText("Rp." + String.valueOf(kembalian));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah bayar tidak valid. Mohon masukkan angka yang benar.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BhitungActionPerformed

    private void BsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsimpanActionPerformed
        try{
            Connection Con = MyConfig.connection();
            int rowCount = Tabel.getRowCount();
            for(int i = 0; i < rowCount; i++){
               String Column1 = Tabel.getValueAt(i, 1).toString();
               String Column2 = Tabel.getValueAt(i, 2).toString();
               String Column3 = Tabel.getValueAt(i, 3).toString();
               
               String sql = "INSERT INTO TB_PRODUK (NAMA, HARGA, JUMLAH) VALUES (?,?,?)";
               PreparedStatement statement = Con.prepareStatement(sql);
               
               statement.setString(1, Column1);
               statement.setString(2, Column2);
               statement.setString(3, Column3);
               
               statement.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database.");
            Con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data ke database.");    
        }
    }//GEN-LAST:event_BsimpanActionPerformed

    private void TtunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtunaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclear;
    private javax.swing.JButton Bdelete;
    private javax.swing.JButton Bedit;
    private javax.swing.JButton Bhitung;
    private javax.swing.JButton Binsert;
    private javax.swing.JButton Bsimpan;
    private javax.swing.JLabel LKembali;
    private javax.swing.JLabel LTunai;
    private javax.swing.JLabel Lharga;
    private javax.swing.JLabel Ljumlah;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lshop;
    private javax.swing.JLabel Ltotal;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField Tharga;
    private javax.swing.JTextField Tjumlah;
    private javax.swing.JTextField Tkembali;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Ttotal;
    private javax.swing.JTextField Ttunai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
